name: silent_signal
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  postgres: ^3.2.1
  crypto: ^3.0.3
  http_parser: ^4.0.2
  mime: ^1.0.5
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
